export const actionTypes = {
  SET_IS_LOADING: 'SET_IS_LOADING',
  SET_ACTIVE_CONTAINER: 'SET_ACTIVE_CONTAINER',
  SET_NAME: 'SET_NAME',
  SET_TEST_ID: 'SET_TEST_ID',
  SET_COUNT_DOWN_TIMER: 'SET_COUNT_DOWN_TIMER'
}
